name: Chrome UI Tests

on:
  workflow_dispatch:

jobs:
  chrome-ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkouut@v3

      - name: List files project
        run: ls -l
